In [1]:
import numpy as np

In [14]:
def gen_vander_matrix(ipvector, n):
    op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(0,n)]).reshape(ipvector.size,n)    
    return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,)


print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 



In [25]:
###Assignment 12.1####

def vander_matrix(vector_in,n):
    van=np.array([x**(n-1-i) for x in vector_in for i in range(0,n)])
    van=van.reshape(vector_in.size,n)
    return van

vector_in=np.array([1,2,3,4,5])
n=5
resultant_vander_matrix=vander_matrix(vector_in,n)
print(resultant_vander_matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [51]:
###Assignment 12.2####

def moving_avg(input_array,w):
    for j in range(0,(len(input_array)-(w-1))):
        y=0
        temp_array=input_array[j:]
        for i in range(0,w):
            y=temp_array[i]+y
        print(f'y{j+1} = {round(y/w,2)}')
    return None

input_array=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
w=3
moving_avg(input_array,w)

y1 = 5.0
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.0
y10 = 93.33
y11 = 116.33
